# Generated by Django 3.0.8 on 2020-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
