# Generated by Django 3.0.8 on 2020-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='academics/library/gallary/')),
            ],
        ),
        migrations.CreateModel(
            name='Library_User_Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_manual', models.FileField(upload_to='academics/library/user_manual/')),
            ],
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_range', models.CharField(help_text='Use this example format: 2019-2020', max_length=9)),
                ('sno', models.IntegerField()),
                ('uSN', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('rank', models.CharField(help_text='Use roman numerals for consistency. For example: I (for 1st rank)', max_length=8)),
                ('course_type', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], max_length=2)),
            ],
        ),
    ]
