# Generated by Django 3.0.8 on 2020-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='placement/gallary/')),
            ],
        ),
        migrations.CreateModel(
            name='Placement_Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(upload_to='placement/')),
            ],
        ),
        migrations.CreateModel(
            name='Placement_Invitaton_For_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.FileField(upload_to='placement/')),
            ],
        ),
    ]
