# Generated by Django 3.0.8 on 2020-08-04 17:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default='1')),
                ('name', models.CharField(max_length=200)),
                ('training_and_placement_designation', models.CharField(max_length=200)),
                ('department_designation', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='placement/staff/image/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='infrastructure_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(default='A321', max_length=10)),
                ('image', models.ImageField(upload_to='placement/infrastructure/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='placement_glimpses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='placement/placement_glimpses/')),
            ],
        ),
        migrations.CreateModel(
            name='pre_placement_glimpses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='placement/pre_placement_glimpses/')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='placement/staff/image/')),
                ('detail', models.FileField(blank='True', upload_to='placement/staff/data/')),
                ('sno', models.IntegerField(default='1')),
                ('staff_type', models.CharField(choices=[('DEAN', 'DEAN'), ('PB', 'PUBLIC RELATION'), ('OTHER', 'OTHER')], default='DEAN', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter description only for DEAN. For others this field can be skipped.')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallary',
        ),
        migrations.DeleteModel(
            name='Placement_Brochure',
        ),
        migrations.DeleteModel(
            name='Placement_Invitaton_For_Company',
        ),
    ]
