# Generated by Django 3.0.8 on 2020-08-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20200804_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
