# Generated by Django 3.0.8 on 2020-08-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_remove_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure_gallery',
            name='room_no',
        ),
        migrations.AddField(
            model_name='infrastructure_gallery',
            name='room_name',
            field=models.CharField(default='A321', max_length=50),
        ),
    ]
