# Generated by Django 3.0.8 on 2020-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_auto_20200806_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure_gallery',
            name='image_type',
            field=models.CharField(choices=[('PH', 'Placement Hall'), ('AUD', 'Auditorium'), ('PBR', 'Placement Board Room'), ('DR', 'Discussion Room'), ('LAB', 'Lab')], default='PH', max_length=100),
        ),
    ]
