# Generated by Django 3.0.8 on 2020-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_infrastructure_gallery_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='hiring_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('image', models.FileField(upload_to='placement/hiring_statistics/')),
            ],
        ),
    ]
