# Generated by Django 3.0.8 on 2020-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_hiring_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank='True', upload_to='placement/staff/image/'),
        ),
    ]
