# Generated by Django 3.0.8 on 2020-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_auto_20200806_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('image', models.ImageField(upload_to='placement/slider/')),
                ('image_caption', models.CharField(max_length=100)),
            ],
        ),
    ]
