# Generated by Django 3.0.8 on 2020-08-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0009_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_glimpses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='placement/training_glimpses/')),
            ],
        ),
    ]
