# Generated by Django 3.0.8 on 2020-08-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0010_training_glimpses'),
    ]

    operations = [
        migrations.CreateModel(
            name='industrial_collabrations_and_mou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('title_of_MOU', models.TextField()),
                ('mOU_signed_with', models.TextField()),
                ('signing_date', models.DateField()),
            ],
        ),
    ]
