# Generated by Django 3.0.8 on 2020-08-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0011_industrial_collabrations_and_mou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrial_collabrations_and_mou',
            name='signing_date',
            field=models.DateField(help_text='Use Format:YYYY-MM-DD or the calender button'),
        ),
    ]
