# Generated by Django 3.0.8 on 2020-12-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0012_auto_20200828_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='placement_updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('detail', models.FileField(blank=True, upload_to='placement/updates/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=25)),
            ],
        ),
    ]
