# Generated by Django 3.0.8 on 2021-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0013_placement_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='media_coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='placement/media_coverage/')),
            ],
        ),
        migrations.CreateModel(
            name='students_placed_glimpses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='placement/students_placed_glimpses/')),
            ],
        ),
    ]
