# Generated by Django 3.0.8 on 2020-07-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20200727_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mca_dept_learning_materials',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='mca_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th')]),
        ),
        migrations.AlterField(
            model_name='mca_dept_timetable',
            name='course',
            field=models.CharField(choices=[('BE', 'B.E.'), ('MT', 'M.Tech'), ('MCA', 'MCA')], default='BE', max_length=100),
        ),
    ]
