# Generated by Django 3.0.8 on 2020-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20200728_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmental_dept_learning_materials',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name='environmental_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')]),
        ),
    ]
