# Generated by Django 3.0.8 on 2020-11-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20200728_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_upcoming_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('detail', models.FileField(blank=True, upload_to='department/CS/event/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=25)),
            ],
        ),
    ]
