# Generated by Django 3.0.8 on 2020-07-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_bio_technology_dept_result_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd')]),
        ),
        migrations.AlterField(
            model_name='mathematics_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')]),
        ),
        migrations.AlterField(
            model_name='physics_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd')]),
        ),
    ]
