# Generated by Django 3.0.8 on 2020-07-15 09:57

import department.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20200715_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='bio_medical_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='bio_technology_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chemical_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='electrical_and_electronics_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_communication_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_instrumentation_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='information_science_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='textile_technology_dept_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bio_technology_dept_result_analysis',
            name='result_analysis_image',
            field=models.ImageField(help_text='Upload image of result analysis bar graph or pie chart', upload_to='department/BM/result-analysis/', validators=[department.models.bio_technology_dept_result_analysis.validate_image]),
        ),
        migrations.AlterField(
            model_name='bio_technology_dept_result_analysis',
            name='result_analysis_pdf',
            field=models.FileField(upload_to='department/BM/result-analysis/'),
        ),
        migrations.AlterField(
            model_name='chemistry_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')]),
        ),
        migrations.AlterField(
            model_name='mathematics_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')]),
        ),
        migrations.AlterField(
            model_name='physics_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')]),
        ),
    ]
