# Generated by Django 3.0.8 on 2020-07-15 10:02

import department.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20200715_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_technology_dept_result_analysis',
            name='result_analysis_image',
            field=models.ImageField(help_text='Upload image of result analysis bar graph or pie chart', upload_to='department/BT/result-analysis/', validators=[department.models.bio_technology_dept_result_analysis.validate_image]),
        ),
        migrations.AlterField(
            model_name='bio_technology_dept_result_analysis',
            name='result_analysis_pdf',
            field=models.FileField(upload_to='department/BT/result-analysis/'),
        ),
        migrations.AlterField(
            model_name='chemistry_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd')]),
        ),
        migrations.AlterField(
            model_name='mathematics_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')]),
        ),
        migrations.AlterField(
            model_name='physics_dept_result_analysis',
            name='semester',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd')]),
        ),
    ]
