# Generated by Django 3.0.8 on 2020-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20200715_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='bio_medical_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='bio_technology_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chemical_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='electrical_and_electronics_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_communication_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_instrumentation_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='information_science_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='textile_technology_dept_classroom_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bio_medical_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='bio_medical_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='bio_technology_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='bio_technology_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='chemical_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='chemical_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='chemistry_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='chemistry_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='civil_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='civil_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='computer_science_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='computer_science_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='electrical_and_electronics_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='electrical_and_electronics_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='electronics_and_communication_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='electronics_and_communication_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='electronics_and_instrumentation_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='electronics_and_instrumentation_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='information_science_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='information_science_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='mathematics_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='mathematics_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='mechanical_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='mechanical_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='physics_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='physics_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='textile_technology_dept_classroom',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
        migrations.AddField(
            model_name='textile_technology_dept_laboratory_facilities_gallary',
            name='room_no',
            field=models.CharField(default='A321', max_length=10),
        ),
    ]
