# Generated by Django 3.0.8 on 2020-07-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20200715_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='bio_medical_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='bio_technology_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='chemical_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='electrical_and_electronics_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_communication_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_instrumentation_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='information_science_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.CreateModel(
            name='textile_technology_dept_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Enter a short description about your department's forum.")),
            ],
        ),
        migrations.AlterField(
            model_name='bio_medical_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='bio_technology_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='chemical_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='chemistry_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='civil_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='computer_science_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='electrical_and_electronics_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='electronics_and_communication_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='electronics_and_instrumentation_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='information_science_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='mathematics_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='mechanical_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='physics_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
        migrations.AlterField(
            model_name='textile_technology_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('RE', 'Forum Activity'), ('STC', 'Department Activity')], default='RE', max_length=500),
        ),
    ]
