# Generated by Django 3.0.8 on 2020-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_auto_20200715_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('STC', 'Department Activity')], default='STC', max_length=500),
        ),
        migrations.AlterField(
            model_name='mathematics_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('STC', 'Department Activity')], default='STC', max_length=500),
        ),
        migrations.AlterField(
            model_name='physics_dept_activities',
            name='activity_type',
            field=models.CharField(choices=[('STC', 'Department Activity')], default='STC', max_length=500),
        ),
    ]
