# Generated by Django 3.0.8 on 2020-07-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drinkingWaterGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='facilities/drinkingWaterGallary')),
            ],
        ),
        migrations.CreateModel(
            name='garbageGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='facilities/garbageGallary')),
            ],
        ),
        migrations.CreateModel(
            name='guestHouseGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='facilities/guestHouseGallary')),
            ],
        ),
    ]
