# Generated by Django 3.0.8 on 2020-07-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_drinkingwatergallary_garbagegallary_guesthousegallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ewasteGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='facilities/ewasteGallary')),
            ],
        ),
    ]
