# Generated by Django 3.0.8 on 2021-03-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_ewastegallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ladiesHostelSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('images', models.ImageField(upload_to='facilities/ladiesHostel/sliderImages')),
            ],
        ),
    ]
