# Generated by Django 3.0.8 on 2020-10-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('detail', models.FileField(upload_to='main_web/notification/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
