# Generated by Django 3.0.8 on 2020-10-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='detail',
            field=models.FileField(blank=True, upload_to='main_web/notification/'),
        ),
    ]
