# Generated by Django 3.0.8 on 2020-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0004_auto_20201022_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
