# Generated by Django 3.0.8 on 2020-11-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0005_auto_20201110_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_added',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='notification',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
