# Generated by Django 3.0.8 on 2020-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PG_addmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseWiseSeatMatrix', models.FileField(upload_to='addmission/PG/')),
                ('notification', models.FileField(default='coming-soon.png', upload_to='addmission/PG/')),
                ('application_form', models.FileField(upload_to='addmission/PG/')),
                ('cut_off', models.FileField(default='coming-soon.png', upload_to='addmission/PG/')),
            ],
        ),
        migrations.CreateModel(
            name='UG_addmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addmission_fee', models.FileField(upload_to='addmission/UG/')),
                ('CourseWiseSeatMatrix', models.FileField(upload_to='addmission/UG/')),
                ('notification', models.FileField(upload_to='addmission/UG/')),
                ('application_form', models.FileField(upload_to='addmission/UG/')),
                ('cut_off', models.FileField(upload_to='addmission/UG/')),
            ],
        ),
    ]
