# Generated by Django 3.0.8 on 2020-12-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_addmission',
            name='CourseWiseSeatMatrix',
            field=models.FileField(blank=True, upload_to='addmission/PG/'),
        ),
        migrations.AlterField(
            model_name='pg_addmission',
            name='application_form',
            field=models.FileField(blank=True, upload_to='addmission/PG/'),
        ),
        migrations.AlterField(
            model_name='pg_addmission',
            name='cut_off',
            field=models.FileField(blank=True, default='coming-soon.png', upload_to='addmission/PG/'),
        ),
        migrations.AlterField(
            model_name='pg_addmission',
            name='notification',
            field=models.FileField(blank=True, default='coming-soon.png', upload_to='addmission/PG/'),
        ),
        migrations.AlterField(
            model_name='ug_addmission',
            name='CourseWiseSeatMatrix',
            field=models.FileField(blank=True, upload_to='addmission/UG/'),
        ),
        migrations.AlterField(
            model_name='ug_addmission',
            name='addmission_fee',
            field=models.FileField(blank=True, upload_to='addmission/UG/'),
        ),
        migrations.AlterField(
            model_name='ug_addmission',
            name='application_form',
            field=models.FileField(blank=True, upload_to='addmission/UG/'),
        ),
        migrations.AlterField(
            model_name='ug_addmission',
            name='cut_off',
            field=models.FileField(blank=True, upload_to='addmission/UG/'),
        ),
        migrations.AlterField(
            model_name='ug_addmission',
            name='notification',
            field=models.FileField(blank=True, upload_to='addmission/UG/'),
        ),
    ]
