# Generated by Django 3.0.8 on 2020-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20201207_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_addmission',
            name='diploma_fee',
            field=models.FileField(blank=True, upload_to='addmission/PG/'),
        ),
    ]
