# Generated by Django 3.0.8 on 2020-12-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_pg_addmission_diploma_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pg_addmission',
            old_name='diploma_fee',
            new_name='addmission_fee',
        ),
        migrations.AddField(
            model_name='ug_addmission',
            name='diploma_fee',
            field=models.FileField(blank=True, upload_to='addmission/UG/'),
        ),
    ]
