# Generated by Django 3.0.8 on 2021-01-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20201212_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)])),
                ('audit_statement', models.FileField(upload_to='addmission/Audit/')),
            ],
        ),
        migrations.CreateModel(
            name='Prospectus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospectus', models.FileField(upload_to='addmission/Prospectus/')),
            ],
        ),
    ]
