# Generated by Django 3.0.8 on 2020-07-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Btech_Technowav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btech_technowav', models.FileField(upload_to='campus_life/btech_technowav/')),
                ('type_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation_Year',
            fields=[
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NAAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(upload_to='campus_life/NAAC/')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campus_life/graduation_day/image/')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_life.Graduation_Year')),
            ],
        ),
    ]
