# Generated by Django 3.0.8 on 2020-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Btech_Technowav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btech_technowav', models.FileField(upload_to='campus_life/btech_technowav/')),
                ('type_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campus_life/graduation_day/image/')),
            ],
        ),
        migrations.CreateModel(
            name='NAAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(upload_to='campus_life/NAAC/')),
            ],
        ),
    ]
