# Generated by Django 3.0.8 on 2020-07-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_life', '0002_gymgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymgallery',
            name='images',
            field=models.ImageField(upload_to='campus_life/gymGallery'),
        ),
    ]
