# Generated by Django 3.0.8 on 2020-11-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_life', '0003_auto_20200727_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='sacGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('images', models.ImageField(upload_to='campus_life/sacGallery')),
            ],
        ),
        migrations.CreateModel(
            name='sacMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_category', models.CharField(choices=[('PRESIDENT', 'President'), ('DEAN SAC', 'Dean SAC'), ('ADVISORS', 'Advisors'), ('CONVENERS', 'Conveners'), ('EXECUTIVE COUNCIL', 'Executive Council'), ('CULTURAL SECRETARIES', 'Cultural Secretaries'), ('SPORT SECRETARIES', 'Sport Secretaries'), ('MAGAZINE SECRETARIES', 'Magazine Secretaries'), ('CANTEEN SECRETARIES', 'Canteen Secretaries'), ('LADY REPRESENTATIVES', 'Lady Representatives'), ('ADVISORY COMMITTEE', 'Advisory Committee')], max_length=100)),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
    ]
