# Generated by Django 3.0.8 on 2020-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_life', '0004_sacgallery_sacmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='sac_Intro_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
