# Generated by Django 3.0.8 on 2021-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_life', '0005_sac_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation_year',
            name='year',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], primary_key=True, serialize=False),
        ),
    ]
