# Generated by Django 3.0.8 on 2020-07-25 10:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender', models.FileField(upload_to='about_biet/calender/')),
            ],
        ),
        migrations.CreateModel(
            name='Deans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('responsibility', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', models.ImageField(upload_to='about_biet/deans/image/')),
                ('description', models.TextField()),
                ('detail', models.FileField(upload_to='about_biet/deans/data/')),
            ],
        ),
        migrations.CreateModel(
            name='Governing_Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='about_biet/governing_body/image/')),
            ],
        ),
        migrations.CreateModel(
            name='Governing_Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='about_biet/governing_council/image/')),
            ],
        ),
        migrations.CreateModel(
            name='Office_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_biet/office/image/')),
                ('sno', models.IntegerField()),
            ],
        ),
    ]
