# Generated by Django 3.0.8 on 2020-07-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office_staff',
            name='detail',
        ),
    ]
