# Generated by Django 3.0.8 on 2020-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognized_Research_Centres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
