# Generated by Django 3.0.8 on 2020-11-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0002_recognized_research_centres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nain_Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('images', models.ImageField(upload_to='about_biet/NAIN_Carousel')),
            ],
        ),
        migrations.CreateModel(
            name='Nain_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('images', models.ImageField(upload_to='about_biet/NAIN_Gallery')),
            ],
        ),
    ]
