# Generated by Django 3.0.8 on 2020-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0003_nain_carousel_nain_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honors_And_Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('faculty', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('name_of_the_award', models.CharField(max_length=500)),
                ('awarded_by', models.CharField(max_length=500)),
                ('awarded_on', models.CharField(max_length=100)),
                ('awarded_for', models.TextField()),
            ],
        ),
    ]
