# Generated by Django 3.0.8 on 2020-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0004_honors_and_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research_Dean_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_biet/research/image/')),
                ('detail', models.FileField(blank=True, upload_to='about_biet/research/data/')),
                ('description', models.TextField()),
            ],
        ),
    ]
