# Generated by Django 3.0.8 on 2020-11-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0005_research_dean_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funded_Projects_Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funded_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('title_of_project', models.TextField()),
                ('funding_agency', models.CharField(max_length=400)),
                ('amount_sanctioned', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_biet.Funded_Projects_Department')),
            ],
        ),
    ]
