# Generated by Django 3.0.8 on 2020-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0006_funded_projects_funded_projects_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='kscst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kscst_pdf', models.FileField(upload_to='about_biet/research/')),
            ],
        ),
    ]
