# Generated by Django 3.0.8 on 2021-01-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0007_kscst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Major_Events_Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_biet/Major_Events')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_biet.Major_Events')),
            ],
        ),
    ]
